apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blackpearlserv-service
  labels:
    app: blackpearlserv-service
    version: v1.0.0
  namespace: pirates
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackpearlserv-service
      version: v1.0.0
  template:
    metadata:
      labels:
        app: blackpearlserv-service
        version: v1.0.0
    spec:
      containers:
      - name: blackpearlserv-service
        image: docker.io/vemahendran/blackpearlserv:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: blackpearlserv-service-config
        ports:
        - containerPort: 9090
          protocol: TCP
          name: http
        livenessProbe:
          tcpSocket:
            port: 9090
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 1
        readinessProbe:
          tcpSocket:
            port: 9090
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
