apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flyingdutchmanserv-service
  labels:
    app: flyingdutchmanserv-service
    version: v1.0.0
  namespace: pirates
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flyingdutchmanserv-service
      version: v1.0.0
  template:
    metadata:
      labels:
        app: flyingdutchmanserv-service
        version: v1.0.0
    spec:
      containers:
      - name: flyingdutchmanserv-service
        image: docker.io/vemahendran/flyingdutchmanserv:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: flyingdutchmanserv-service-config
        ports:
        - containerPort: 9095
          protocol: TCP
          name: http
        livenessProbe:
          tcpSocket:
            port: 9095
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 1
        readinessProbe:
          tcpSocket:
            port: 9095
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
